// SPDX-License-Identifier: AGPL-3.0-only
export * from "./manifest.js";
export * from "./host.js";
export { collect, DETECTORS, type CollectOptions } from "./collect.js";
export { nodeHost } from "./live-host.js";
export { firstLine } from "./detect/common.js";
export type { Detector } from "./detect/common.js";
export { detectIdentity } from "./detect/identity.js";
export { detectShell } from "./detect/shell.js";
export { bareSources, guardSources, shellSources } from "./detect/sources.js";
export { GUARD_BEGIN, GUARD_END, calledCommands, dropPlugins, guardCommands } from "./detect/commands.js";
export { TERMINAL_FONT_ID, alacrittyFont, detectTerminalFont, ghosttyFont, itermFont, kittyFont, weztermFont } from "./detect/terminal.js";
export { detectToolchains } from "./detect/toolchains.js";
export { detectTools, parseBrewfile, parseBunGlobals, parseCargoInstalls, parseGoVersionM, parseNpmGlobals, parsePipxList, parsePnpmGlobals, parseUvToolList, type BrewLine, type GoModule, type Pkg } from "./detect/tools.js";
export { classifyFormulae, linuxSupport, renderSnapshot, type BottleSnapshot } from "./brew-bottles.js";
export { LINUX_BOTTLES } from "./data/linux-bottles.js";
export { AGENTS, detectAgents } from "./detect/agents.js";
export { type Presence, presenceOf } from "./detect/presence.js";
export * from "./history/index.js";
export { type CommandCount, type RecipeOptions, computeRecipe, floorApplies, unknownCommands, withProject } from "./recipe.js";
export { PROJECT_READERS, type ProjectNeed, type ProjectScan, scanProject } from "./project/index.js";
export type { ProjectFile, ProjectFinding, ProjectReader } from "./project/reader.js";
export { MCP_BIN_DIRS, MCP_REMOTE_ID, MCP_REMOTE_LABEL, detectMcp, homePaths, linuxFit, mcpRemoteHash, type LinuxFit } from "./detect/mcp.js";
export { CLAUDE_KEY_ENV, apiKeyHelperOf, detectLogins } from "./detect/logins.js";
export { FISH_CONF_D, RC_NAMES, RC_PATHS, isRcPath, isSecretName, rcFiles, simpleCommands, sourcedPaths, stripExports } from "./detect/shell-rc.js";
export { type Signal, MAX_BYTES, bareUrls, fileSignals, keysSignal, modeSignal, nameSignal, pemSignal, topLevelKeys, urlSignal } from "./credential-signals.js";
export { CACHE_DIRS, FINDER_METADATA } from "./cache-names.js";
